#!/usr/bin/env python3

import src.convertSUD as Sud
import fileinput


def main():
    sudoku = "".join(list(fileinput.input())[1:])
    # print the CNF to stdout
    print(Sud.convert(sudoku))


if __name__ == "__main__":
    main()
