#!/usr/bin/env python3

import fileinput

import src.convertSUD as Sud


def main():
    sudoku = "".join(list(fileinput.input())[1:])
    # print the CNF to stdout
    print(Sud.convert(sudoku))


if __name__ == "__main__":
    main()
