#!/usr/bin/env python3

from src.convertCNF import Encoding
import src.convertCNF as Cnf
import fileinput
import argparse


def main():
    sudoku = "".join(fileinput.input())
    parser = argparse.ArgumentParser(
        description='Convert a sudoku puzzle to CNF')
    parser.add_argument('-e', '--encoding', type=str, default='minimal',
                        help='Encoding to use (minimal, efficient, extended)')

    args = parser.parse_args()
    encoding = Encoding.MINIMAL
    match args.encoding:
        case 'efficient':
            encoding = Encoding.EFFICIENT
        case 'extended':
            encoding = Encoding.EXTENDED
    # print the CNF to stdout
    print(Cnf.convert(sudoku, encoding))


if __name__ == "__main__":
    main()
